//using System;
//using System.Collections;
//using System.Collections.Generic;
//using UnityEngine;

//public class Rewarded : MonoBehaviour
//{

//    string adUnitId = "1882960987cccae9";
//    int retryAttempt;

//    // Start is called before the first frame update
//    void Start()
//    {
//        // Attach callback
//        MaxSdkCallbacks.Rewarded.OnAdLoadedEvent += OnRewardedAdLoadedEvent;
//        MaxSdkCallbacks.Rewarded.OnAdLoadFailedEvent += OnRewardedAdLoadFailedEvent;
//        MaxSdkCallbacks.Rewarded.OnAdDisplayedEvent += OnRewardedAdDisplayedEvent;
//        MaxSdkCallbacks.Rewarded.OnAdClickedEvent += OnRewardedAdClickedEvent;
//        MaxSdkCallbacks.Rewarded.OnAdRevenuePaidEvent += OnRewardedAdRevenuePaidEvent;
//        MaxSdkCallbacks.Rewarded.OnAdHiddenEvent += OnRewardedAdHiddenEvent;
//        MaxSdkCallbacks.Rewarded.OnAdDisplayFailedEvent += OnRewardedAdFailedToDisplayEvent;
//        MaxSdkCallbacks.Rewarded.OnAdReceivedRewardEvent += OnRewardedAdReceivedRewardEvent;

//        // Load the first rewarded ad


//    }

//    public void LoadRewardedAd()
//    {
//        MaxSdk.LoadRewardedAd(adUnitId);
//    }

//    private void OnRewardedAdLoadedEvent(string adUnitId, MaxSdkBase.AdInfo adInfo)
//    {
//        // Rewarded ad is ready for you to show. MaxSdk.IsRewardedAdReady(adUnitId) now returns 'true'.
//        MaxSdk.ShowRewardedAd(adUnitId);
//        // Reset retry attempt
//        retryAttempt = 0;
//    }

//    private void OnRewardedAdLoadFailedEvent(string adUnitId, MaxSdkBase.ErrorInfo errorInfo)
//    {
//        // Rewarded ad failed to load 
//        // AppLovin recommends that you retry with exponentially higher delays, up to a maximum delay (in this case 64 seconds).

//        retryAttempt++;
//        double retryDelay = Math.Pow(2, Math.Min(6, retryAttempt));

//        Invoke("LoadRewardedAd", (float)retryDelay);
//    }

//    private void OnRewardedAdDisplayedEvent(string adUnitId, MaxSdkBase.AdInfo adInfo) { }

//    private void OnRewardedAdFailedToDisplayEvent(string adUnitId, MaxSdkBase.ErrorInfo errorInfo, MaxSdkBase.AdInfo adInfo)
//    {
//        // Rewarded ad failed to display. AppLovin recommends that you load the next ad.
//        LoadRewardedAd();
//    }

//    private void OnRewardedAdClickedEvent(string adUnitId, MaxSdkBase.AdInfo adInfo) { }

//    private void OnRewardedAdHiddenEvent(string adUnitId, MaxSdkBase.AdInfo adInfo)
//    {
//        // Rewarded ad is hidden. Pre-load the next ad
       
//    }

//    private void OnRewardedAdReceivedRewardEvent(string adUnitId, MaxSdk.Reward reward, MaxSdkBase.AdInfo adInfo)
//    {
//        // The rewarded ad displayed and the user should receive the reward.
//    }

//    private void OnRewardedAdRevenuePaidEvent(string adUnitId, MaxSdkBase.AdInfo adInfo)
//    {
//        // Ad revenue paid. Use this callback to track user revenue.

//        // Update is called once per frame
//        void Update()
//        {

//        }
//    }
//}
